Repository prgrms-app-devcourse/-1-Project4-Final-team4, pull requests merged in 2024-05, with the labels that each got.

#14 #13 - fix: 공통 컴포넌트 수정, Colors 변수이름 수정
  src/components/AddScheduleInput.jsx
  src/components/BasicHeader.jsx
  src/components/CustomBottomTab.jsx
  src/components/MainHeader.jsx
  src/pages/Community.jsx
  src/pages/EditProfile.jsx
  src/pages/Home.jsx
  src/pages/MyPage.jsx
  src/pages/ScheduleList.jsx
  src/pages/Search.jsx
  src/pages/Splash.jsx
  src/utils/Colors.js
Labels: 준영, fix

#15 #15- Feature:로그인 회원가입 기능 구현
  .env.d.ts
  .gitignore
  App.tsx
  android/gradle/wrapper/gradle-wrapper.properties
  babel.config.js
  package-lock.json
  package.json
  src/auth.ts
  src/pages/ForgotPassword.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: 윤서

#17 Feat/home main
  .eslintrc.js
  .gitignore
  App.tsx
  android/gradle/wrapper/gradle-wrapper.properties
  package-lock.json
  package.json
  react-native.config.js
  src/assets/fonts/Pretendard.otf
  src/assets/fonts/PretendardBold.otf
  src/assets/fonts/PretendardLight.otf
  src/assets/icons/searchIcon.png
  src/assets/images/food1.jpg
  src/assets/images/johnWick.png
  src/assets/images/madness.png
  src/assets/images/movie1.jpg
  src/assets/images/place1.jpg
  src/assets/images/place2.jpg
  src/assets/images/place3.jpg
  src/assets/images/reviewFrame.png
  src/components/BasicHeader.jsx
  src/components/CategoryButton.jsx
  src/components/MainHeader.jsx
  src/pages/Home.jsx
  src/router.js
  src/utils/Colors.js
Labels: 지민

#24 [FIX] dev 최신 변경 사항 충돌 해결
  .gitignore
  ios/Podfile.lock
  ios/get_ready_with_p.xcodeproj/project.pbxproj
  ios/get_ready_with_p/AppDelegate.mm
  ios/get_ready_with_p/Info.plist
  package.json
  src/pages/EditProfile.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/pages/ScheduleList.jsx
  src/router.js
Labels: 준영

#32 [IOS] 파이어베이스 테스트
  android/app/build.gradle
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/get_ready_with_p.xcodeproj/project.pbxproj
  ios/get_ready_with_p/AppDelegate.h
  ios/get_ready_with_p/AppDelegate.mm
  src/libs/firebase.js
  src/pages/Logintest.jsx
Labels: 준영

#33 [PAGE] 지역검색 화면 구현
  android/build.gradle
  package.json
  patches/react-native-geolocation-service+5.3.1.patch
  src/components/CategoryButton.jsx
  src/pages/LocationSearchMap.jsx
Labels: 서진

#35 [PAGE] 테마별 검색 페이지 및 api 호출 구현
  .gitignore
  package.json
  src/apis/movie.js
  src/apis/place.js
  src/apis/show.js
  src/assets/images/placeholder.jpg
  src/components/BasicHeader.jsx
  src/components/CategoryButton.jsx
  src/components/CustomCarousel.jsx
  src/components/MainHeader.jsx
  src/pages/Home.jsx
  src/pages/ThemeSearch.jsx
  src/router.js
  src/utils/Colors.js
Labels: 지민

#39 [FIX] 안드로이드 파일 수정
  .gitignore
  android/app/src/main/AndroidManifest.xml
  src/pages/LocationSearchMap.jsx
Labels: bug, 서진

#40 [FIX] dev 동기화
  package.json
  src/components/CommunityArticle.jsx
  src/components/CommunityButton.jsx
  src/components/CustomBottomTab.jsx
  src/pages/AddFeed.jsx
  src/pages/Article.jsx
  src/pages/ArticleDetail.jsx
  src/pages/Calculator.jsx
  src/pages/Calendar.jsx
  src/pages/Community.jsx
  src/pages/CommunityAdd.jsx
  src/pages/Feed.jsx
  src/pages/FeedDetail.jsx
  src/pages/Help.jsx
  src/pages/Home.jsx
  src/pages/LocationSearch.jsx
  src/pages/Search.jsx
  src/pages/Settings.jsx
  src/pages/Sports.jsx
  src/utils/Colors.js
Labels: 준영

#43 [FIX] 스케줄 리스트
  src/hook/use-schedule-list.jsx
  src/pages/ScheduleList.jsx
  src/router.js
Labels: 준영

#46 [README] 리드미 수정
  README.md
  image-1.png
  image-2.png
  image-3.png
  image-4.png
  image-5.png
  image-6.png
  image-7.png
  image.png
  src/assets/images/fire.png
  src/assets/images/js.png
  src/assets/images/logo_fullname.png
  src/assets/images/page.jpg
  src/assets/images/rn.png
Labels: 준영

#45 [REFACTOR] 커뮤니티 페이지 리팩토링
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/PretendardMedium.otf
  src/components/CategorySelectButton.jsx
  src/components/CommunityArticle.jsx
  src/components/SortButton.jsx
  src/pages/Community.jsx
  src/pages/CommunityAdd.jsx
Labels: 동현

#49 [REFACTOR] 마이페이지, 수정페이지 수정
  src/components/CustomBottomTab.jsx
  src/pages/EditProfile.jsx
  src/pages/MyPage.jsx
  src/utils/utils.js
Labels: 준영

#50 [REFACTOR] 일정 페이지 수정
  src/pages/ScheduleList.jsx
Labels: 준영

#51 [REFACTOR] 마이페이지 수정
  src/pages/MyPage.jsx
Labels: 준영

#53 FEAT: 커뮤니티 페이지 최신순/추천순 정렬 기능 구현
  .gitignore
  package-lock.json
  src/components/CategorySelectButton.jsx
  src/components/CommunityArticle.jsx
  src/components/SortButton.jsx
  src/pages/Community.jsx
  src/pages/CommunityAdd.jsx
Labels: 동현

#55 [FEATURE, REFACTOR, DESIGN]: 도움말 페이지 제작 및 MyPage Refactoring 및 디자인 수정
  src/assets/images/help1.jpg
  src/assets/images/help2.jpg
  src/assets/images/help3.jpg
  src/assets/images/help4.jpg
  src/assets/images/help5.jpg
  src/assets/images/help6.jpg
  src/assets/images/help7.jpg
  src/assets/images/help8.jpg
  src/pages/Help.jsx
  src/pages/MyPage.jsx
  src/router.js
Labels: 지민

#56 [FEAT] 커뮤니티 게시물 추가 페이지 이미지 선택 기능 구현
  src/hook/use-addPost.jsx
  src/pages/CommunityAdd.jsx
Labels: 준영

#57 [FEAT] API 호출을 통한 명소를 Map뷰 및 마커로 출력
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  src/apis/location.js
  src/apis/movie.js
  src/apis/place.js
  src/pages/ContentDetail.jsx
  src/pages/LocationSearchMap.jsx
  src/pages/ThemeSearch.jsx
  src/router.js
Labels: 지민, 서진

#59 [REFACTOR] QA를 통한 UI/UX 수정
  src/pages/AccountBook.jsx
  src/pages/AccountBookPlus.jsx
  src/pages/CommunityAdd.jsx
  src/pages/ContentDetail.jsx
  src/pages/Home.jsx
  src/pages/LocationSearchMap.jsx
  src/pages/MyPage.jsx
  src/pages/ThemeSearch.jsx
Labels: enhancement
